import{a as x,S as v,i as c}from"./assets/vendor-Dy2ZTtfi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const P="50870264-4cff09f0574465c81a14bcda1",S="https://pixabay.com/api/";async function m(o,e=1){const s={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,lang:"en",per_page:15,page:e},{data:a}=await x(S,{params:s});return{maxPages:Math.ceil(a.totalHits/s.per_page),images:a.hits}}const g=document.querySelector(".loader"),p=document.querySelector(".btn");function f(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}function q(){y.innerHTML=""}function h(){p.classList.remove("hidden")}function C(){p.classList.add("hidden")}const y=document.querySelector(".gallery"),M=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function b(o){const e=o.map(({webformatURL:s,largeImageURL:a,tags:t,likes:r,views:i,comments:L,downloads:w})=>`<li class="gallery-item">
  <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${t}"
    />
  </a>
  <ul>
  <li><span class="spanText">Likes</span><br>${r}</li>
  <li><span class="spanText">Views</span><br>${i}</li>
  <li><span class="spanText">Comments</span><br>${L}</li>
  <li><span class="spanText">Downloads</span><br>${w}</li>
  </ul>
</li>`).join("");y.insertAdjacentHTML("beforeend",e),M.refresh()}let n=1;const d=document.querySelector(".form");d.addEventListener("submit",T);let l;async function T(o){if(o.preventDefault(),f(),q(),l=d.elements["search-text"].value.trim(),l==="")return u(),c.show({message:"❌ you must write something!!",backgroundColor:"red",position:"topRight"});n=1;try{const{images:e,maxPages:s}=await m(l,n);if(e.length===0)return c.show({message:"❌ Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",position:"topRight"});b(e),n<s&&h()}catch(e){let s="Щось пішло не так. Спробуйте ще раз пізніше.";e.response&&e.response.status>=500?s="Сервер тимчасово недоступний, вибачте за незручності":e.response&&e.response.status>=400&&(s="Невірний запит або недоступний ресурс. Перевірте введені дані."),c.show({message:s,backgroundColor:"red",position:"topRight"})}finally{u(),d.reset()}}p.addEventListener("click",$);async function $(){n++,C(),f();try{const{images:o,maxPages:e}=await m(l,n);b(o);const s=document.querySelector(".gallery-item"),{height:a}=s.getBoundingClientRect();n<e&&h(),n>=e&&c.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"blue",position:"topRight"}),window.scrollBy({top:a*2,behavior:"smooth"})}catch(o){let e="Щось пішло не так. Спробуйте ще раз пізніше.";o.response&&o.response.status>=500?e="Сервер тимчасово недоступний, вибачте за незручності":o.response&&o.response.status>=400&&(e="Невірний запит або недоступний ресурс. Перевірте введені дані."),c.show({message:e,backgroundColor:"red",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
